const people = [
  'Barack Obama',
  'Donald Trump',
  'Joe Biden',
  'Bernie Sanders',
  'Elizabeth Warren',
  'Kamala Harris',
  'Mike Pence',
  'Nancy Pelosi',
  'Chuck Schumer',
  'Steve Jobs',
  'Bill Gates',
  'Mark Zuckerberg',
  'Jeff Bezos',
  'Elon Musk',
  'Lady Gaga',
  'Taylor Swift',
  'Justin Bieber',
  'Kanye West',
  'Kim Kardashian',
  'Beyonce',
  'Rihanna',
  'Katy Perry',
  'Miley Cyrus',
  'Ariana Grande',
  'Selena Gomez',
  'Justin Timberlake',
  'Brad Pitt',
  'Leonardo DiCaprio',
  'Tom Cruise',
  'Will Smith',
  'Dwayne Johnson',
  'Chris Hemsworth',
  'Chris Evans',
  'Robert Downey Jr',
  'Scarlett Johansson',
]

export { people }

export default people
